// Class automatically generated by Dev-C++ New Class wizard

#ifndef CUENTA_H
#define CUENTA_H
#include "pedidodomicilio.h"
#include "pedido.h"
#include "pedidomesa.h"
// No description
class Cuenta
{string nombre;
long nit;
Pedido*p;
	public:
		// class constructor
		Cuenta(Pedido*);
		// class destructor
		~Cuenta();
		void imprimir();
		long getTotales();
};

#endif // CUENTA_H
