// Class automatically generated by Dev-C++ New Class wizard

#ifndef ESPECIALES_H
#define ESPECIALES_H
#include "item.h" 
// No description
class Especiales:public Item
{
string Nombre;
Item **especial;
int tam;
long precioTot;
	public:
		// class constructor
		Especiales(string, Item**, int);
		Especiales();
		// class destructor
		~Especiales();
//		void salvar();
//		long getCant();
		long getPrecioTot();
       void mostrar();      
       string getNombre();
       void operator=(Especiales);
};

#endif // ESPECIALES_H
