// Class automatically generated by Dev-C++ New Class wizard

#include "especiales.h" // class's header file

// class constructor
Especiales::Especiales(string n,Item**j,int tam1)
{
Nombre=n;
tam=tam1;
especial=new Item*[tam];
for(int i=0;i<tam;i++)
{
  (*(especial+i))=(*(j+i));
}
long x=0;
for(int i=0;i<tam;i++)
{
  x=x+(*(especial+i))->getPrecio();
}
precioTot=x;
}

Especiales::Especiales()
{
	// insert your code here
}
Especiales::~Especiales()
{
	// insert your code here
}
void Especiales::mostrar()
{
cout<<"Nombre especial:          "<<Nombre<<endl<<endl;
cout<<"Ingredientes:             "<<endl<<endl;
for(int i=0;i<tam;i++)
{
  (*(especial+i))->mostrar();
  cout<<"_________________________________"<<endl;
  
}
cout<<"Precio Total:      "<<precioTot<<endl;
}
long Especiales::getPrecioTot()
{return precioTot;}
string Especiales::getNombre()
{return Nombre;}
void Especiales::operator=(Especiales e)
{
for(int i=0;i<e.tam;i++)
{
  (*(especial+i))=(*(e.especial+i));
}
}
