// Class automatically generated by Dev-C++ New Class wizard

#ifndef ITEM_H
#define ITEM_H
#include <cstdlib>
#include <iostream>
#include <string.h>
using namespace std;
// No description
class Item
{protected:
string nombre;
string descripcion;
long precio;
long cantidad;          
	public:
		// class constructor
		Item(string, string,long,long);
		Item();
		// class destructor
		~Item();
		void salvar();
		long getCant();
		string getNombre();
		long getPrecio();
		void operator=(Item);
		void mostrar();
		void leer();
};

#endif // ITEM_H
