// Class automatically generated by Dev-C++ New Class wizard

#include "menu.h" // class's header file

// class constructor
Menu::Menu(Item **j, int tam1)
{
tam=tam1;
menu=new Item*[tam];
for(int i=0;i<tam;i++)
{
  (*(menu+i))=(*(j+i));
}
}

// class destructor
Menu::~Menu()
{
	// insert your code here
}
bool Menu::buscar(string nombre, int pos)
{

     if(pos>(tam-1))
     return 0;
     else
     {
          if(pos<tam)
          {
                 if((*(menu+pos))->getNombre()==nombre)
                 {return pos;
                 (*(menu+pos))->mostrar();}
                 else
                 return buscar(nombre, pos+1);

          }


     }
}
bool Menu::buscar(int cantidad, int pos)
{

     if(pos>(tam-1))
     return 0;
     else
     {
          if(pos<tam)
          {
                 if((*(menu+pos))->getCant()>cantidad)
                 {return pos;
                 (*(menu+pos))->mostrar();}
                 else
                 return buscar(cantidad, pos+1);

          }


     }
}
void Menu::mostrar()
{
for(int i=0;i<tam;i++)
{
  (*(menu+i))->mostrar();
  cout<<"_________________________________"<<endl;
  
}

}
