// Class automatically generated by Dev-C++ New Class wizard

#ifndef MENU_H
#define MENU_H
#include "item.h"
// No description
class Menu
{
Item **menu;
int tam;

	public:
		// class constructor
		Menu(Item**, int);
		// class destructor
		~Menu();
		bool buscar(string, int);
		bool buscar(int, int);
		void mostrar();
//		bool disponible(int);
};

#endif // MENU_H
