// Class automatically generated by Dev-C++ New Class wizard

#ifndef ORDEN_H
#define ORDEN_H
#include "menu.h"
#include <stdlib.h> // for itoa() call # Include <stdlib.h> / / para itoa () llamada
#include <stdio.h> // for printf() call # Include <stdio.h>
// No description
class Orden
{
Item **pedidos;
int tam;
string cant;
int total;
char mat[20][20];
	public:
		// class constructor
		Orden();
		// class destructor
		~Orden();
		void leer();
		long getTotal();
		bool verificar(string);
		bool verificar2(string);
		int conversor(int);
		void mostrar();

};

#endif // ORDEN_H
