// Class automatically generated by Dev-C++ New Class wizard

#include "pedidomesa.h" // class's header file

// class constructor
PedidoMesa::PedidoMesa(Orden** o, int tam1, long codig, int mesa)
:Pedido(o,tam1,codig)
{
mesa=mesa;
}

// class destructor
PedidoMesa::~PedidoMesa()
{
	// insert your code here
}
long PedidoMesa::totalCancelar()
{
return Pedido::totalCancelar()+(3*100/(Pedido::totalCancelar()));
}
void PedidoMesa:: mostrar()
{Pedido::mostrar();
cout<<"Mesa ocupada:       "<<mesa<<endl;
}
