// Class automatically generated by Dev-C++ New Class wizard

#include "pedido.h" // class's header file

// class constructor
Pedido::Pedido(Orden** o, int tam1, long codig)
{
codigo=codig;
tam=tam1;
lista=new Orden*[tam];
for(int i=0;i<tam;i++)
{
  (*(lista+i))=(*(o+i));
}
}

// class destructor
Pedido::~Pedido()
{
	// insert your code here
}
long Pedido::totalCancelar()
{
for(int i=0;i<tam;i++)
{
  montoTot=montoTot+(*(lista+i))->getTotal();
}
}
string Pedido::actualizadorEstado()
{

for(int contador=0;contador<600;contador++)
{
        if(contador<120)
        cout<<"Preparando";
        
        if(contador>300 & contador<500)
        cout<<"Pendiente de entrega";
       
}
}
void Pedido::mostrar()
{
for(int i=0;i<tam;i++)
{
  (*(lista+i))->mostrar();
}
cout<<"Monto total a pagar:       "<<montoTot<<endl;
}
