// Class automatically generated by Dev-C++ New Class wizard

#ifndef PEDIDO_H
#define PEDIDO_H
#include "orden.h"
// No description
class Pedido
{
protected:
Orden**lista;
int tam;
long codigo;
string estado;
int montoTot;
	public:
		// class constructor
		Pedido(Orden**, int, long);
		// class destructor
		~Pedido();
		long totalCancelar();
		string actualizadorEstado();
		void mostrar();
};

#endif // PEDIDO_H
