// Class automatically generated by Dev-C++ New Class wizard

#include "pedidodomicilio.h" // class's header file

// class constructor
PedidoDomicilio::PedidoDomicilio(Orden** o, int tam1, long codig,string dir,string nom)
:Pedido(o,tam1,codig)
{
direccion=dir;
nombre=nom;
}

// class destructor
PedidoDomicilio::~PedidoDomicilio()
{
	// insert your code here
}
long PedidoDomicilio::totalCancelar()
{
return Pedido::totalCancelar()+8;
}
void PedidoDomicilio::mostrar()
{Pedido::mostrar();
cout<<"Direccion del cliente:       "<<direccion<<endl;
cout<<"Nombre del cliente:         "<<nombre<<endl;
}
