// Class automatically generated by Dev-C++ New Class wizard

#include "restaurante.h" // class's header file

// class constructor
Restaurante::Restaurante(Cuenta ** c, int tam1)
{
tam=tam1;
cuentas=new Cuenta*[tam];
for(int i=0;i<tam;i++)
{
  (*(cuentas+i))=(*(c+i));
}
}

// class destructor
Restaurante::~Restaurante()
{
	// insert your code here
}
long Restaurante::getTotalVendido()
{granTotal=0;
for(int i=0;i<tam;i++)
{
  granTotal=granTotal+(*(cuentas+i))->getTotales();
}
}
