// Class automatically generated by Dev-C++ New Class wizard

#ifndef RESTAURANTE_H
#define RESTAURANTE_H
#include "cuenta.h"
// No description
class Restaurante
{Cuenta **cuentas;
int tam;
int granTotal;
	public:
		// class constructor
		Restaurante(Cuenta ** c, int tam1);
		// class destructor
		~Restaurante();
		long getTotalVendido();
};

#endif // RESTAURANTE_H
